version: '3'

services:

  php:
    build: 
      context: .
    volumes:
      - ./:/var/www/html

  web:
    image: nginx:alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MY_SQL_ROOT_HOST: "%"
      MY_SQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MY_SQL_DATABASE: "${DB_DATABASE}"
      MY_SQL_USER: "${DB_USERNAME}"
      MY_SQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    volumes:
      - redisdata:/data    
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 
    depends_on:
      - db
  node:
    image: node:22-alpine
    user: node
    working_dir: /assets
    volumes:
      - ./:/assets
    command: npm run watch
volumes:
  mysqldata:
  redisdata:

